### ISSUE TITLE
Get unix/timestamp

### ISSUE THREAD

**Issue by hosseinGanjyar** [fingerpich/jalali-angular-datepicker#103]
This isn't a bug! I want a solution for:
How to get unix time from selected date, same as **1535879620549**?
Thanks

**Comment by fingerpich** [comment]
Search for moment and unix format
you should ask this kind of questions in stackoverflow, please!

**Comment by hosseinGanjyar** [comment]
Have you understood my issue?
I've solved this:
moment(1569492703, 'jYYYY/jMM/jDD HH:mm').unix()

**Comment by fingerpich** [comment]
Somehow but I thought you can find better solution in the SO.
