### ISSUE TITLE
افزودن تابعی برای رندر سلول های جدول

### ISSUE THREAD

**Issue by ghamshekan** [fingerpich/jalali-angular-datepicker#105]
با توجه به نیازهای تجاری مختلف اگر امکان رندر سفارشی سلول های تقویم توسط کاربر افزوده شود کارایی کامپوننت بسیار افزایش می یابد
(چیزی شبیه تابع render در Datatable)
![image](https://user-images.githubusercontent.com/47173733/55775537-db34f100-5aae-11e9-8a20-1b85890d5bbd.png)
به عنوان نمونه برنامه نویس توانسته مبلغ را در روزهای مختلف درون جدول بگنجاند

**Comment by fingerpich** [comment]
Hi,
good idea
Feel free to create a PR
Thanks
