### ISSUE TITLE
initial date

### ISSUE THREAD

**Issue by elibushehri** [fingerpich/jalali-angular-datepicker#106]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by elibushehri** [comment]
hi
I want to simply set an initial date but I cant.
I save a shamsi date in persian font and in english font and try to assign it to the datepicker when page initialized. I used writevalue and also tried to assign value to ngmodel data or datepicker component but nothing happens
please help me.

**Comment by fingerpich** [comment]
Hi,
If you changed characters to persian number you have to convert characters before you assign the value to the datepicker
and also as I mentioned in the [document](https://github.com/fingerpich/jalali-angular-datepicker#how-to-use) you have to pass a moment object not a string
