### ISSUE TITLE
dayBtnFormatter not work well

### ISSUE THREAD

**Issue by ghamshekan** [fingerpich/jalali-angular-datepicker#107]
I used config for format button 
 ```
datePickerConfig={
      format: 'dddd D MMMM YYYY',
      min:moment(),
      closeOnSelect:true,
      appendTo:"#datefrom",
      dayBtnFormatter : (day:any) => {
        return moment(day).locale('fa').format('DD')+   '<br />'+ this.mydata(day);
      },
      dayBtnCssClassCallback : (day: any) => {
         return 'mybtnday'
      },
};
```
dayBtnFormatter and dayBtnCssClassCallback ,but html show me un-rendered Tag <br/>
and mybtnday is as low prority and not affected
![image](https://user-images.githubusercontent.com/47173733/57680994-0e394a00-7644-11e9-9505-0d900bc6479d.png)

- [ ] What's the **version** of Angular you're using? 7

**Comment by fingerpich** [comment]
**dayBtnFormatter** should be passed a string not a node

**dayBtnCssClassCallback** has done what it expected to do, the problem is in your css
