### ISSUE TITLE
error invalid when select specific days likes 1398-02-30 and 1398-02-31 and 1398-02-29

### ISSUE THREAD

**Issue by ehsan69h** [fingerpich/jalali-angular-datepicker#108]
when i select specific dates like 1398-02-30 and 1398-02-31 and 1398-02-29. show me date not valid and not submit forms.
i test that in demo page [demo](https://fingerpich.github.io/jalali-angular-datepicker)

**Comment by fingerpich** [comment]
The problem is in jalali-moment
so we will fix it in [this issue](https://github.com/fingerpich/jalali-moment/issues/61)
