### ISSUE TITLE
After selecting the date, it will not close

### ISSUE THREAD

**Issue by archive-me** [fingerpich/jalali-angular-datepicker#116]
After selecting the date, it will not close?!?!?!
Why?

**Comment by mm580486** [comment]
Usually this shouldn't happen, can u share your code in stackblitz

**Comment by kia9372** [comment]
i have this problem too . this occure when i need to use  angular material input  .

this is config :
`	datePickerConfigFa_Down: {
		// drops: 'down',
		format: 'YYYY/MM/DD',
		showTwentyFourHours: 'enabled',
		closeOnSelect: true,
		showMultipleYearsNavigation: 'enabled',
		locale: 'fa',
		drops: 'down',
	},`

and this is Html Code :

`            <mat-form-field appearance="outline">
                        <mat-label>{{'MAGAZINE_SHARE.CREATE_REGISTER_TO' | translate}} </mat-label>
                        <input formControlName="endDate" theme="dp-material"
                         matInput mode="day" [dpDayPicker]="datePickerConfigEnd" />
                        <mat-datepicker-toggle matSuffix></mat-datepicker-toggle>
                    </mat-form-field>`

but when i select the date it not closed .

**Comment by fingerpich** [comment]
Fixed in /pull/115
