### ISSUE TITLE
How can I change the month names? or make it Numerical.

### ISSUE THREAD

**Issue by azad47808** [fingerpich/jalali-angular-datepicker#117]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by sediqamousavi** [comment]
@azad47808  you can set Month Button Format (monthBtnFormat) to MM or M

**Comment by sediqamousavi** [comment]
@azad47808  You can set Month Format (monthFormat) to MM YYYY or M YY
datePickerConfig = {
        monthFormat: 'MM YYYY'
 }
