### ISSUE TITLE
need to change the styles for the input field how and where i can do that?

### ISSUE THREAD

**Issue by sakenk** [fingerpich/jalali-angular-datepicker#119]
can i do that?

**Comment by mm580486** [comment]
you can applying the ::ng-deep( or /deep/ depends your angular version) pseudo-class to any css code , when u using this combinator u can access every element in your page or other component 
So then u most use some code like this
```
# Angular 9
::ng-deep .dp-picker-input {
   color: #fuckingred;
}
# Angular 2 ~ 8
/deep/ .dp-picker-input {
   color: #fuckingred;
}
```

also u can write your custome style in `./project_path/src/styles.(s)css`
It depends on yourself 😉
