### ISSUE TITLE
Update NPM

### ISSUE THREAD

**Issue by minahmoghadam** [fingerpich/jalali-angular-datepicker#124]
Dear Mojtaba, I used the NPM to install date picker and I have some issues that you fixed in the git master branch. 
Is it possible to update the https://www.npmjs.com/package/ng2-jalali-date-picker module version?

**Comment by mm580486** [comment]
@minahmoghadam  Please explain more about your problem

**Comment by minahmoghadam** [comment]
The issue is about showing the first day of Farvardin month twice in the Safari browser.

**Comment by fingerpich** [comment]
Please check v2.4.1.
