### ISSUE TITLE
using Renderer2 

### ISSUE THREAD

**Issue by beingJimmy** [fingerpich/jalali-angular-datepicker#127]
please consider replacing usage of Renderer with Renderer2, so it would be compatible with angular 9 since it has removed the deprecated Renderer

- [9.1.7 ]  **angular version**

**Comment by fingerpich** [comment]
It has been done in this [PR](https://github.com/fingerpich/jalali-angular-datepicker/pull/122)
have you installed to v2.4.1?

**Comment by beingJimmy** [comment]
yes- I have v2.4.1 installed but it seems it's been missed in 2 of package files

**Comment by fingerpich** [comment]
can you please create a PR?

**Comment by beingJimmy** [comment]
sure- done that. #128

**Comment by fingerpich** [comment]
thanks. check v2.4.2.
