### ISSUE TITLE
Duplicate day numbers

### ISSUE THREAD

**Issue by aligorji** [fingerpich/jalali-angular-datepicker#130]
Follow https://fingerpich.github.io/jalali-angular-datepicker/#
In "Day Picker directive", This problem can also be seen in the demo version:
tested on:
iPhone 7+  ios13.2.3 Safari and chrome

![image](https://user-images.githubusercontent.com/8667938/87873364-54bbce80-c9d6-11ea-82d1-b650f9b65d78.png)

**Comment by fingerpich** [comment]
Duplicate #129

**Comment by fingerpich** [comment]
Its fixed. the problem caused by jajali-moment.
