### ISSUE TITLE
Clear selected Date by Button

### ISSUE THREAD

**Issue by nkm96** [fingerpich/jalali-angular-datepicker#131]
Hi, 
How can I clear selected date by clicking on a button? 
I already tried:
- change selected date parameter to null
- change selected date parameter to undefined
- change selected date parameter to "" or ''
- pipe value to selected date

after these ways, It seems my parameter could be set correctly, and problem is just in html tag 'dp-date-picker' and just on view.

**Comment by fingerpich** [comment]
Please create a demo then we would help to make it work.

**Comment by nkm96** [comment]
Thanks for quick responding!
I made a demo on StackBlitz and it worked correctly.
Then I understood that I was using previous version of your component. So I updated it to 2.4.2 and now everything is okay.
