### ISSUE TITLE
node-sass dependecy

### ISSUE THREAD

**Issue by saeedrahimi** [fingerpich/jalali-angular-datepicker#133]
Hi, Thanks for your great date-picker.

All styles in this library are written in `less` files and there is no `sass` or `scss` files.
`node-sass` itself is also deprecated.
Is it necessary to have `node-sass` as a direct dependency?

**Comment by saeedrahimi** [comment]
I can make a PR if u want

**Comment by fingerpich** [comment]
Thanks, It seems you are right
Can you please check it and create a PR?

**Comment by oleksiy-ryabchuk** [comment]
Hi folks, I believe this change is not yet availbale in the package version 2.4.2 published in npm. Are there any plans to publish newer version?
