### ISSUE TITLE
after api.open() it does not show the selected date

### ISSUE THREAD

**Issue by mghazy** [fingerpich/jalali-angular-datepicker#17]
dude thank you !! i was struggling to find jallali date picker in angular 2  !!
the problem is when the date is selected in component after api.open() it does not show the selected date and instead it just show the current date box.

**Comment by fingerpich** [comment]
Hi , it's my pleasure.
i did what you said in [demo](https://fingerpich.github.io/jalali-angular-datepicker/) and it was OK.
can you please make a demo or explain me more?

**Comment by mghazy** [comment]
1- create a component in your app 
2- set default value(any date but not in current month) in by setting [(ngModel)]="a moment type variable"
3- after clicking the input, the box opens on current month instead of the month been selected.
i suggest you to set the value in demo on constructor or OnInit to **moment('1395-11-22','jYYYY,jMM,jDD');**

**Comment by fingerpich** [comment]
thank you. it is fixed in v1.5.2
just run `npm install ng2-jalali-date-picker --save`

**Comment by mghazy** [comment]
you are my hero bro 👍
