### ISSUE TITLE
persian date

### ISSUE THREAD

**Issue by reza3vi** [fingerpich/jalali-angular-datepicker#20]
how to get persian date in model?

**Comment by fingerpich** [comment]
its using jalali system by default as you see in  [demo](https://fingerpich.github.io/jalali-angular-datepicker/).
what do you mean about "persian date"?

**Comment by reza3vi** [comment]
hi. are didam. khodam az in estefade kardam. barash style neveshtam shode
mesle primeng

**Comment by fingerpich** [comment]
I mean it generates a date like 1396/4/13 which is a valid date in persian (jalali) system.
could you explain me more the problem?
