### ISSUE TITLE
default date format consideration

### ISSUE THREAD

**Issue by mghazy** [fingerpich/jalali-angular-datepicker#21]
i think its better to set default date format to "YYYY-MM-DD" instead of "DD-MM-YYYY" due to the fact that almost all iranian and afghanies use this kind of format.
thank you my brother

**Comment by fingerpich** [comment]
Thank you bro. I have done this on [demo](https://fingerpich.github.io/jalali-angular-datepicker/) but I missed a line. I will fix it.

**Comment by fingerpich** [comment]
its fixed in [1.5.4](https://www.npmjs.com/package/ng2-jalali-date-picker).
thank you.
