### ISSUE TITLE
RTL style problem

### ISSUE THREAD

**Issue by mghazy** [fingerpich/jalali-angular-datepicker#22]
when setting the component to RTL the circle icon comes on the date text.
but there is no problemn using it in LTR mode.
the simplest solution is to set LTR as a default attribute of element.
thank you my brother

**Comment by fingerpich** [comment]
Its fixed in [1.5.4](https://www.npmjs.com/package/ng2-jalali-date-picker).
[demo](https://fingerpich.github.io/jalali-angular-datepicker/) is updated too.
thank you.
