### ISSUE TITLE
How to set Configurations?

### ISSUE THREAD

**Issue by mohammad-shadmehr** [fingerpich/jalali-angular-datepicker#23]
Hi,
Can you provide a sample on how to set the configuration while attaching it to a control? i have got the following code and works fine and once I add the "calendarSystem:ECalendarSystem.jalali" it crashes!
` <input name="startDate" class="form-control" [(ngModel)]="schedule.startDate" theme="dp-material" [dpDayPicker]="{format:'DD-MM-YYYY', calendarSystem:ECalendarSystem.jalali}" />`

**Comment by fingerpich** [comment]
Hi
jalali is default calendar system
but yes you can not change it to gregorian, because you haven't access to ECalendarSystem
thank you!

**Comment by fingerpich** [comment]
Its fixed in [1.5.5](https://www.npmjs.com/package/ng2-jalali-date-picker).
install new version and you could import ECalendarSystem enum as following code
 
`import {ECalendarSystem} from 'ng2-jalali-date-picker';`

Thank you.
