### ISSUE TITLE
Include Time to the picker?

### ISSUE THREAD

**Issue by mohammad-shadmehr** [fingerpich/jalali-angular-datepicker#26]
Any chance to have time included in the component? Perhaps an attribute for time-only or date-only or both?

**Comment by fingerpich** [comment]
Hi,
i am afraid to say no
its only a datepicker you could use another component for time picker.

**Comment by fingerpich** [comment]
Hi,
yes, it will be done.

**Comment by mohsensrmst** [comment]
Hi
how do use time in this component?!

**Comment by fingerpich** [comment]
its done.
[demo link](https://fingerpich.github.io/jalali-angular-datepicker/)
