### ISSUE TITLE
High resource consumption in multiple datepickers of page.

### ISSUE THREAD

**Issue by lvlohammadi** [fingerpich/jalali-angular-datepicker#29]
Hi Mojtaba, Thank you for the service.
I encountered a serious problem with multiple `jalali-angular-datepicker` and `jalali-moment` so i thought it might be useful to inform you about it.

**The problem**

1. When we put one date picker on page, everything looks good, Have a lock at cpu usage and `jalali-moment` functions:

![photo_2017-09-13_01-48-26](https://user-images.githubusercontent.com/5156411/30348733-a7460ab6-9825-11e7-8194-9f53c72c8636.jpg)

2. When we have multiple (4-5) date pickers on page, We encounter a lazy page, Have a lock at cpu usage and `jalali-moment` functions. You can see that is not normal and it make the pages too lazy:

![photo_2017-09-13_01-52-53](https://user-images.githubusercontent.com/5156411/30348921-49645d8e-9826-11e7-85b1-0c8c9e3856c0.jpg)

and also without any datepickers:
![photo_2017-09-13_01-57-47](https://user-images.githubusercontent.com/5156411/30349102-f5844610-9826-11e7-98d7-45b79336f325.jpg)

I'm using `jalali-angular-datepicker` as directive method.

**Comment by fingerpich** [comment]
Hi,
Thank you
I have just reproduce your problem in [this demo](https://plnkr.co/edit/7fsNVU)
and I will try to improve its performance and I would appreciate if you could help.

**Comment by lvlohammadi** [comment]
@fingerpich Hi and thanks for reply.
Unfortunately, My problem was more intense than your plnkr demo. Just because I have many views and actually a UI, so i make all date pickers to masked input for now and i would be really appreciate if you find a solution to this issue.
Thank you again.

**Comment by lvlohammadi** [comment]
Any progress on this?

**Comment by fingerpich** [comment]
in latest version we increased its speed please check it.
