### ISSUE TITLE
datepicker input with default Gregorian date

### ISSUE THREAD

**Issue by mehrjouei** [fingerpich/jalali-angular-datepicker#30]
Is it possible to have a for example "edit" form with filled data that birthday input date have Gregorian date and after load date picker show date in jalali?
I want to bind and initialize datepicker with gregorian date But user see jalali date and can modifiy it in jalali.

**Comment by fingerpich** [comment]
Hi
if you want to convert gregorian date to jalali use jalali moment

```js
import * as moment from 'jalali-moment';
let input = '1989/01/24';
var momentObj = moment( input );
```
```html
[(ngModel)]="momentObj"
```
and if you want to choose a jalali date but the input shows gregorian date use the folowing config
```html
[config]="{format:'YYYY-MM-DD'}"
```
