### ISSUE TITLE
'closeOnSelect' option in daytime mode

### ISSUE THREAD

**Issue by srh-ocean1991** [fingerpich/jalali-angular-datepicker#32]
Hi
It will be good if we have 'closeOnSelect' option in daytime mode too. currently this option only is available in day and month mode.

**Comment by fingerpich** [comment]
Hi
thank you
sorry for delay.
I think its not a common issue as you see no one has liked your issue
please fork the project and make your own calendar as you want.

**Comment by Rouhollah** [comment]
'closeOnSelect' Not Working On daytime Mode. version 2.2.7

> Hi
> It will be good if we have 'closeOnSelect' option in daytime mode too. currently this option only is available in day and month mode.

right, it doesn't work. why ? and how to solve ?
