### ISSUE TITLE
detect value of input was changed

### ISSUE THREAD

**Issue by omidkh68** [fingerpich/jalali-angular-datepicker#33]
hi, I used directive mode of datePicker, I want to detect when user select a day, some method of component class will execute, how can I do that?

**Comment by fingerpich** [comment]
Hi,
Why dont you use change event on input?
```html
<input (change)="dosomething()"
````

**Comment by omidkh68** [comment]
@fingerpich it didn't work, I don't know why but I tested this code but it didn't work!

this is my html and method:
`<input type="text" id="date" autocomplete="off" (change)="changed()" [(ngModel)]="selectedDate" [dpDayPicker]="config" theme="dp-material" attachTo=".datePicker1" appInputTyping>`

`changed($event) {
    console.log($event);
  }`

**Comment by omidkh68** [comment]
@lvlohammadi Thank you so much, my problem did solved. 👍
