### ISSUE TITLE
ورود دستی تاریخ در فیلد

### ISSUE THREAD

**Issue by parisamashinchi** [fingerpich/jalali-angular-datepicker#34]
چگونه میتوانم تاریخ را به صورت دستی وارد کنم و خودکار فرمت تعریف شده تاریخ را در فیلد اعمال کنم
1396-01-01 را که وارد میکنم خودش جدا کنه . در واقع میخواهم mask تعریف کنم .

**Comment by fingerpich** [comment]
Hi,
if you used format:'jYYYY-jMM-jDD' it would parse it well but if you wanted to help users more I highly recommend using [cleave.js](https://github.com/nosir/cleave.js) to do this.
