### ISSUE TITLE
Georgian Initial value is not automatically converted to jalali date

### ISSUE THREAD

**Issue by GHR-Arash** [fingerpich/jalali-angular-datepicker#35]
well the component is working fine , but how to show already exsist
<input name="someName" class="form-control" [(ngModel)]="announcement.ExpirationDate" [dpDayPicker]="datePickerConfig" theme="dp-material"/>

and here is my date : 
2001/10/21

I expect this to be shown as jalali date in someName text box , but it is not . 
am i missing something ?

**Comment by fingerpich** [comment]
Hi,
I think the next code will help you

```js
 import * as moment from 'jalali-moment';
announcement.ExpirationDate = moment('2001/10/21');
```
