### ISSUE TITLE
decrease rendering speed when using multiple date picker fields

### ISSUE THREAD

**Issue by miladkiaei** [fingerpich/jalali-angular-datepicker#36]
after triggering every event when using multiple date picker fields in a single page, all of date picker fields will be updated and as a result all of button labels should be updated. so a lot of unneeded function calls will be happened and it can decrease page speed and consume memory and use GPU to render them. it will be tangible specially when scrolling page.
I handled this problem by adding ChangeDetectionStrategy.OnPush to the changeDetection decorator of DayCalendarComponent. please fix this issue.

**Comment by lvlohammadi** [comment]
Yes. This is a major problem and I hope to @fingerpich resolve it sooner.
https://github.com/fingerpich/jalali-angular-datepicker/issues/29

**Comment by fingerpich** [comment]
Hi,
Thank you
could you provide a pull request?
