### ISSUE TITLE
performance بسیار پایین و سرعت نمایش خیلی کم

### ISSUE THREAD

**Issue by sasanazizi** [fingerpich/jalali-angular-datepicker#40]
با سلام و خسته نباشید
بنده مشکل سرعت لود و نمایش و همچنین استفاده‌‌ی بسیار شدید دارم و میخواستم اگر امکانش هست راهنمایی بفرمایید

**Comment by fingerpich** [comment]
Hi,
Thank you
I am working on its performance but if you have some suggestion you could make pull request.

**Comment by fingerpich** [comment]
have you tested the new version?
