### ISSUE TITLE
Is this compatible with angular 1?

### ISSUE THREAD

**Issue by mehrdaad** [fingerpich/jalali-angular-datepicker#41]
Title suggests:  
> Highly configurable jalali (shamsi, khorshidi, persian) date picker built for Angular ( 2 or 4 ) applications  

Is it also compatible with angular 1 too?

**Comment by fingerpich** [comment]
Hi,
It is possible but its not easy and recommended
search about "How to use angular 2 component in angular 1"

**Comment by mehrdaad** [comment]
thanks
