### ISSUE TITLE
make timezone configurable

### ISSUE THREAD

**Issue by mokey1** [fingerpich/jalali-angular-datepicker#42]
hi
i use jalali-angular-datepicker in angular4.4/.net core project. i select a date from datepicker and send it to my core web api , but in my core web api i get wrong date.
In debugging mode i check date model and see this:
"Sat Nov 25 2017 08:58:39 GMT+0330 (Iran Standard Time)"
but in core web api  i get this value:
{24/11/2017 08:30:00 ب.ظ}

when i set "_isUTC" to "true" in date model everything is work well!
There is no way that i set this property in datepicker config?
thanks

**Comment by fingerpich** [comment]
hi
Thank you. I will look at it.

**Comment by mokey1** [comment]
is any change for this issue?

**Comment by fingerpich** [comment]
Hi,
No i didn't but if you provide a pull request for it I will merge it.
