### ISSUE TITLE
Do not compatible with angular 5 

### ISSUE THREAD

**Issue by alirezavafaee** [fingerpich/jalali-angular-datepicker#43]
Please make this compatible with angular 5.
Thank you

**Comment by ahmadalli** [comment]
@alirezavafaee are you getting errors with angular 5? as far as I know, angular 5 didn't have much breaking change the would affect components

**Comment by fingerpich** [comment]
[a demo](https://plnkr.co/XJSWtt) which is using the latest version of angular
