### ISSUE TITLE
customize theme and input field

### ISSUE THREAD

**Issue by alikarimii** [fingerpich/jalali-angular-datepicker#44]
i want customize theme.how do it?

**Comment by alikarimii** [comment]
i found it.
ng2-jalali-date-picker  ->  date-picker  ->  date-picker.component.metadata.json
found style there

**Comment by fingerpich** [comment]
Hi,
I am sorry I thought I have responded but I didn't
you could override its css as the following example
```
/deep/ dp-date-picker {
       .dp-calendar-nav-container{
                  background: #464646 !important;
                  color: #ffffff;
       }
}
```

**Comment by alieshghi** [comment]
thanks for your nice date picker, but I was wondering how we can change style when we use dp-material theme, which you offer to us. for example the width of date picker is 252px  by default , and I want to change it to 170px, so as I do something like that :
```
dp-date-picker.dp-material .dp-picker-input {
    -webkit-box-sizing: border-box;
    box-sizing: border-box;
    height: 30px;
    width: 170px // 252px;
    font-size: 13px;
    outline: none;
}
```
but After change and back to browser to see result, it is not changing and still the with is 252. I think it is not overriding the theme. or even adding the z-index .
