### ISSUE TITLE
استفاده از کلاس های بوت استرپ

### ISSUE THREAD

**Issue by MansoorJafari** [fingerpich/jalali-angular-datepicker#47]
سلام
ببخشید چطور میشه از کلاس form-control 
boostrap برای انتخاب تاریخ استفاده کرد؟

تشکر

**Comment by fingerpich** [comment]
Hi,
you could use directive mode
see the [https://fingerpich.github.io/jalali-angular-datepicker](demo)

**Comment by MansoorJafari** [comment]
تشکر
لینک خرابه
