### ISSUE TITLE
diffrent names in npm and in import

### ISSUE THREAD

**Issue by molikh** [fingerpich/jalali-angular-datepicker#49]
[X] bug:
If you install through npm you will see created a folder named 'ng2-jdate-picker'
but in installation guide you mention we should add this to our app:
import {DpDatePickerModule} from 'ng2-jalali-date-picker' 

I assume should be changed to this one:
import {DpDatePickerModule} from 'ng2-jdate-picker'

thanks for your effort

**Comment by fingerpich** [comment]
Hi,
Thank you
Please install it with the following command
```
npm install ng2-jalali-date-picker --save
```
