### ISSUE TITLE
problem in year 1397 , first month, no 1397/01/02 available!

### ISSUE THREAD

**Issue by saeedshokoohi** [fingerpich/jalali-angular-datepicker#51]
Hi,
There something wrong in day-picker 
In year 1397 , there is not date 1397/01/02
!!

**Comment by fingerpich** [comment]
Hi,
thank you
its fixed. [the demo](https://fingerpich.github.io/jalali-angular-datepicker/)

**Comment by natanzi** [comment]
Dear
Would you please update Npm version also?

**Comment by fingerpich** [comment]
it has updated already its 2.2.1.
[plunker demo](https://plnkr.co/edit/XJSWtt?p=preview) uses the last version and its OK.
