### ISSUE TITLE
persian number

### ISSUE THREAD

**Issue by MetaiR** [fingerpich/jalali-angular-datepicker#54]
Hi,
i want to know is there any way to write numbers in persian, for example show ۲ instead of 2

**Comment by fingerpich** [comment]
#45

**Comment by MetaiR** [comment]
could u please put it in your README.md?

**Comment by abbassafaiean** [comment]
hi
Please refer to the font that contains Persian numbers.
؟

**Comment by fingerpich** [comment]
Ok I will.

**Comment by fingerpich** [comment]
These two font are awesome
[vazir](https://github.com/rastikerdar/vazir-font)
[iransans](http://fontiran.com/%D8%AE%D8%A7%D9%86%D9%88%D8%A7%D8%AF%D9%87-%D9%81%D9%88%D9%86%D8%AA-%D8%A7%DB%8C%D8%B1%D8%A7%D9%86-%D8%B3%D9%86-%D8%B3%D8%B1%DB%8C%D9%81-iran-sans-%D9%BE%D9%86%D8%AC-%D9%88%D8%B2%D9%86-%D9%87%D9%85/)

**Comment by MetaiR** [comment]
it also can be fixed with `loadPersian()` method which is missed on your `jalali-moment` library

for example, [this](https://www.npmjs.com/package/moment-jalaali) is another library for cast Georgian date to Jalali which has that method and it also famous (more than 7K dl on last month) but because of your nice and useful date-picker and also for avoiding of several library for casting date I prefer to use your library for casting my dates.

could u add this method to your library?

**Comment by fingerpich** [comment]
Hi
yes I have removed it because it makes some problem when we want to reproduce the moment object from the string it has generated by its format method.
for example the following code doesn't work.
```
var a = moment();
a.loadPersian();
moment(a.format('jYYYY/jMM/jDD'), 'jYYYY/jMM/jDD');
```
you could use another library or [this code](https://gist.github.com/fingerpich/6108b5d1248abe8bf7e30df72f30a8ae) to have persian numbers
