### ISSUE TITLE
Datepicker not working on Angular 5

### ISSUE THREAD

**Issue by faridv** [fingerpich/jalali-angular-datepicker#55]
I'm trying to use this calendar in my project but I keep getting these errors.
![capture](https://user-images.githubusercontent.com/854874/36779405-1d226606-1c85-11e8-9de3-39dba9f98a09.JPG)

My setup is quite simple, with the following code:

```
<dp-date-picker
    dir="rtl"
    [(ngModel)]="dateObject"
    format="DD-MM-YYYY"
    class="form-control-sm"
    mode="day"
    placeholder="تاریخ"
    theme="dp-material">
</dp-date-picker>
```
Here is my configurations:

```
    angular-cli v1.7.1
    angular v5.2.3
    moment 2.20.1
```

**Comment by fingerpich** [comment]
Hi,
sorry for delay
how do you set the ```dateObject```?

**Comment by mokey1** [comment]
@fingerpich 
i have same issue in angular 5.2.0
my angular component:
```
import * as moment from 'jalali-moment';
 datePickerConfig = {
        drops: 'down',
        format: 'jYYYY/jMM/jDD',
        locale: 'fa',
        appendTo: 'html',
        opens: 'right'
    }
let date=new Date(); // or any format of date
this.dateObject=moment(date)
```

**Comment by fingerpich** [comment]
[the demo](https://fingerpich.github.io/jalali-angular-datepicker/) is also using angular 5 and its OK.
so the problem is not about its compatibility with angular 5.

**Comment by mokey1** [comment]
@fingerpich 
i get error in jalal-moment.js 
![jalali](https://user-images.githubusercontent.com/33902075/37957304-d7f6191c-31c2-11e8-84be-934625c820e0.png)

**Comment by fingerpich** [comment]
so why don't you install the new version?
please install the new version of ng2-jalali-date-picker
```npm install ng2-jalali-date-picker --save```

**Comment by fingerpich** [comment]
could you please reproduce the problem? (in plunker or stackblitz)
