### ISSUE TITLE
Today button (.dp-current-location-btn) show the wrong date

### ISSUE THREAD

**Issue by alirezavafaee** [fingerpich/jalali-angular-datepicker#57]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
No code required.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
the current [Official Demo](https://fingerpich.github.io/jalali-angular-datepicker/) has this problem as well
- [ ] Provide **screenshots** where appropriate
![untitled](https://user-images.githubusercontent.com/16059160/37021067-6d53c4c8-2133-11e8-8eb9-39d3ca8c43b8.png)
- [ ] What's the **version** of Angular you're using?
Whatever demo version is using,
- [ ] Does this occur on specific browser?
Tested in Chrome, Edge and Firefox

**Comment by fingerpich** [comment]
Thank you,
its fixed now [the demo](https://fingerpich.github.io/jalali-angular-datepicker/)
