### ISSUE TITLE
A bug in changing dates by keyboard

### ISSUE THREAD

**Issue by ssz360** [fingerpich/jalali-angular-datepicker#61]
When a persian date (in input) changes by keyboard the component converts it to the wrong date (date in inputs should be written in the Gregorian to convert to persian equivalent date)

![image](https://user-images.githubusercontent.com/5657438/37360485-9ff73ad6-2705-11e8-8e54-32f75f288740.png)

I founded out that the date should be passed to "selected" function in Gregorian (when date is selected by datepicker the "selected" function recieves date in Gregorian but when the input is changed by keyboard the function receives date in Persian) so I tested it By adding the`value = moment(value, 'jYYYY/jM/jD').format('YYYY-MM-DD');` line to the onViewDateChange function it works as it should be.

` if (this.dayPickerService.isValidInputDateValue(value, this.componentConfig)) {
    
  value = moment(value, 'jYYYY/jM/jD').format('YYYY-MM-DD');
   
   this.selected = this.dayPickerService.convertInputValueToMomentArray(value, this.componentConfig);
      this.currentDateView = this.selected.length
        ? this.utilsService.getDefaultDisplayDate(
          null,
          this.selected,
          this.componentConfig.allowMultiSelect,
          this.componentConfig.min,
          this.componentConfig.locale
        )
        : this.currentDateView;
    }`

By changing the `let dateFormat = 'YYYY-MM-DD';` line to `let dateFormat = 'jYYYY-jMM-jDD';` in getDefaultFormatByMode function in the date-picker.service.ts file I get the right results too but I don't know what this change other effects could be.

**Comment by fingerpich** [comment]
#59
