### ISSUE TITLE
Change month names

### ISSUE THREAD

**Issue by javidsapand** [fingerpich/jalali-angular-datepicker#67]
Hi
How can I change the month names?
In Afghanistan, we have different month names for Hijri-Shamsi calendar

**Comment by fingerpich** [comment]
Hi
try the following code
```
import * as moment from 'jalali-moment';
moment().localeData()._month[0] = 'ماه اول'
```

**Comment by javidsapand** [comment]
It worked but didn't reflect in datepicker, I want to change the name of months in datepicker

**Comment by javidsapand** [comment]
@fingerpich It worked but didn't reflect in datepicker, I want to change the name of months in datepicker. can I do that, I am waiting for your response.

**Comment by fingerpich** [comment]
Hi, 
sorry for delay
You could also format it in any way you like with monthBtnFormatter.

**Comment by fingerpich** [comment]
by using monthBtnFormatter
```
config = {
monthBtnFormatter:(month) => {
     return 'جوز-ثور-سرطان-اسد-سنبله-میزان-عقرب-قوس-جدی-دلو-حوت'.split('-')[month];
}
```
by changing the locale data
```
import * as moment from 'jalali-moment';
moment.localeData('fa')._jMonths =  'جوز-ثور-سرطان-اسد-سنبله-میزان-عقرب-قوس-جدی-دلو-حوت'.split('-');
```

**Comment by javidsapand** [comment]
@fingerpich, any solution sir, or I should do some custom work.

**Comment by javidsapand** [comment]
Changing the locale data worked for me.
Thank you so much, sir
