### ISSUE TITLE
Problem with Reactive Forms in edit scenario (setting default value for control)

### ISSUE THREAD

**Issue by tttpco** [fingerpich/jalali-angular-datepicker#68]
I get persian date string from the API, and set it as the value of the FormControl:

`this.projectForm.controls['startDate'].setValue(response.startDate); // '1397/03/10'`

And it works fine. However, when I get the form value, the date passes as Miladi date to the server:

`this.prjService.editProject(this.projectForm.value).subscribe(); //  startDate: 'its Mildai equivalent'`

I also have set a default format for control via config:

`datePickerConfig = {
        format: 'jYYYY/jMM/jDD'
    };`

And the control declaration:

`dp-date-picker dir="rtl" 
                                    formControlName="startDate" 
                                    mode="day" 
                                    placeholder="تاریخ شروع" 
                                    theme="dp-material"
                                    [config]="datePickerConfig">
                                </dp-date-picker>`

What's wrong?

**Comment by aminsaghi-ir** [comment]
This behavior occurs only if I set the default value (as mentioned above) and NOT change the date by the control. 

When I change the dates by the control itself, the problem disappears and works fine!

**Comment by mmirzaeyan** [comment]
i have this problem too , exactly as @aminsaghi-ir said .

**Comment by mmirzaeyan** [comment]
i'm using 2.2.6.
in my case the value it's not moment object , it's just a String and i think that i can't format it before send it to server.

**Comment by mmirzaeyan** [comment]
@fingerpich  what is wrong ? i have to use the moment format ?

**Comment by fingerpich** [comment]
I think the problem is in using jalali date directly.
Please use the following code or make a demo in plunker to make the problem clear.
 
```
import moment from 'jalali-moment'
const jm = moment.from(response.startDate, 'fa', 'YYYY/MM/DD');
this.projectForm.controls['startDate'].setValue(jm);
```

**Comment by mmirzaeyan** [comment]
you tell that is set value with 2 way binding and ngModel is incorrect ? i think a nice plugin like this must have this feature !!

**Comment by fingerpich** [comment]
No I only passed a moment object instead of string

**Comment by mmirzaeyan** [comment]
as you know i cant use moment as type , so what is the type of this property in your model ?
