### ISSUE TITLE
Year changes when editing text field

### ISSUE THREAD

**Issue by DarrenHart1989** [fingerpich/jalali-angular-datepicker#69]
**Description**
When you edit an already selected date with the keyboard, i.e change a value (years, month, day, hour, minute or second) it changes the year to somewhere in the future. This occurs in the Demo also. 

**Start**
![image](https://user-images.githubusercontent.com/3176372/40779265-2f3cc856-64cc-11e8-8f71-411efa561cbf.png)

**Selected Date**
![image](https://user-images.githubusercontent.com/3176372/40779277-418be744-64cc-11e8-97a4-2872d21a4565.png)

**Delete seconds**
![image](https://user-images.githubusercontent.com/3176372/40779296-52b310a6-64cc-11e8-8a76-0ec40c8be668.png)

**Add seconds back in**
![image](https://user-images.githubusercontent.com/3176372/40779327-700da03a-64cc-11e8-9c66-f9c6f8e50160.png)

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
- [x] [demo](https://fingerpich.github.io/jalali-angular-datepicker/)
- [x] Provide **screenshots** where appropriate
- [x] Demo system version
- [x] Chrome

**Comment by DarrenHart1989** [comment]
@fingerpich when will this make it into a release?

**Comment by fingerpich** [comment]
I have just done it.
sorry for delay
