### ISSUE TITLE
how to style datepicker input

### ISSUE THREAD

**Issue by MammadK** [fingerpich/jalali-angular-datepicker#70]
how to remove default style for input and more importantly add class to `<dp-date-picker>`  to effect rendered datepicker input?

**Comment by fingerpich** [comment]
https://github.com/fingerpich/jalali-angular-datepicker/issues/44

**Comment by MammadK** [comment]
when i add a class for example `form-control` to `<dp-date-picker>` template and build project it will be removed from input and wrapping div in DOM.

how can add bootstarp class to input?

**Comment by fingerpich** [comment]
Hi,
That is because of angular encapsulation and using /deep/ in CSS is work around to make some changes on a web component style.
