### ISSUE TITLE
template do not follow Angular css-encapsulation 

### ISSUE THREAD

**Issue by MammadK** [fingerpich/jalali-angular-datepicker#71]
as shown below, for some reason [angular css encapsulation attributes](https://angular.io/guide/component-styles#view-encapsulation) only applies to the `dp-date-picker` element and not child elements.

![code](https://user-images.githubusercontent.com/16358451/41556974-745de800-7351-11e8-8b7e-553cb37424d7.png)
--------
as you can see, after compilation, angular add unique attributes to all html elements and styles that belongs to a component. so it's important to fix this issue otherwise any costume styling will not apply to datepicker...thanks

![code3](https://user-images.githubusercontent.com/16358451/41559273-d1a93eea-7358-11e8-9d54-ff2fa70ceb00.png)
------
![code](https://user-images.githubusercontent.com/16358451/41558399-ea8b4474-7355-11e8-9d4d-b40c3d4850ee.png)
--------
![code 2png](https://user-images.githubusercontent.com/16358451/41558595-8467f628-7356-11e8-93c0-1d67ebf91df8.png)

**Comment by fingerpich** [comment]
#44
