### ISSUE TITLE
feature request: add forRoot() for module to config datepicker format globally

### ISSUE THREAD

**Issue by hadirsa** [fingerpich/jalali-angular-datepicker#72]
I think it's good to have forRoot() in module to pass some configs like date format and ... .
is it possible?

**Comment by fingerpich** [comment]
Hi,

Could you please explain more what you expect **forRoot()** do for you?
Do you expect **forRoot()** changes default config for all Date Pickers or override them?

**Comment by hadirsa** [comment]
@fingerpich hi, for example i want to pass this config object in forRoot():
`  datePickerConfig = {format: 'jYYYY/jMM/jDD'};`
to take effect on all data pickers in modules.

**Comment by fingerpich** [comment]
Do you expect forRoot() changes default config for all Date Pickers or override them?

**Comment by hadirsa** [comment]
@fingerpich  Yes, exactly. Currently  we must define config in every component or pass it inline.

**Comment by fingerpich** [comment]
I said there is two way
1- forRoot() changes default config for every calendar
2- forRoot() override used config for every calendar
which one?

**Comment by azizkhani** [comment]
What is diff btw 1,2?

**Comment by fingerpich** [comment]
1 - A datepicker has a default config but if you changed the config for a datepicker forRoot() wouldn't change your config
2 - forRoot() wouldn't care about your change and all of them will change.

**Comment by azizkhani** [comment]
Any library have this feature , developer can change default configuration when import that by forRoot  , for example page size in pagination can change using forRoot and ,but developer can change page size for each component when using that ,

**Comment by fingerpich** [comment]
If you already know it please make a fork and send pr

**Comment by hadirsa** [comment]
Ok i'll try to do this.
