### ISSUE TITLE
how customize them??

### ISSUE THREAD

**Issue by masoudDaliriyan** [fingerpich/jalali-angular-datepicker#74]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [x] Provide a **minimal code snippet**, please make sure it is well formatted.
- [x] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by fingerpich** [comment]
Are you asking about how to change its style? #44
