### ISSUE TITLE
Error on biding datepicker model value on edit mode

### ISSUE THREAD

**Issue by hadirsa** [fingerpich/jalali-angular-datepicker#81]
- [ * ] bug 

I have a sample code which uses dp-date-picker, everything is Ok and working except on editing form which has dp-date-picker is in. Value displayed in input is in Jalali format but value is't.
I have stackblitz whitch has this problem too. 
Online:
    https://angular-je2t9c.stackblitz.io/
Edit:
    https://stackblitz.com/edit/angular-je2t9c
What is wrong?

**Comment by fingerpich** [comment]
As you see in [document](https://github.com/fingerpich/jalali-angular-datepicker) model object is moment instance which is use [jalali-moment](https://www.npmjs.com/package/jalali-moment)

so when you need to use its value as jalali date you have to format it as the following code
```
{{dataObject.date.format('YYYY/MM/DD')}}
```

**Comment by hadirsa** [comment]
I close this issue due to #83
