### ISSUE TITLE
how to get string format from time select

### ISSUE THREAD

**Issue by mmirzaeyan** [fingerpich/jalali-angular-datepicker#82]
hi 
how can i get string time format like 10:30 or 16:40 from time select ?

**Comment by fingerpich** [comment]
Hi,

Change the format property to 'HH:MM'

**Comment by mmirzaeyan** [comment]
it's not work if you need i can give a stackblitz sample to try it .
thanks a lot .

**Comment by fingerpich** [comment]
you can test it in [demo](https://fingerpich.github.io/jalali-angular-datepicker/#)
set the date format HH:mm

**Comment by mmirzaeyan** [comment]
https://stackblitz.com/edit/angular-kuxqgy 
please see this sample , i think i have to reformat the output but i dont know how

**Comment by fingerpich** [comment]
I thought you want to show only hour and minutes but I see you would like to format it as 24 hours format.
As you see in [time select configuration properties](https://github.com/fingerpich/jalali-angular-datepicker#inline---time-select) you can use the following config to do that
```
config = { showTwentyFourHours: true }
```

https://stackblitz.com/edit/angular-ngskaf
