### ISSUE TITLE
set empty value to date picker 

### ISSUE THREAD

**Issue by mmirzaeyan** [fingerpich/jalali-angular-datepicker#87]
i want to set an empty value to dateObject :
```
dateObject = moment('1395-11-22','jYYYY,jMM,jDD');

<dp-date-picker 
   dir="rtl"
   [(ngModel)]="dateObject"
   mode="day"
   placeholder="تاریخ"
   theme="dp-material">
 </dp-date-picker>

```
if i set the dateObject to empty like this : 
this.dateObject="";
and next time when i want to get date with dateObject.format(this.dateObject,"fa" ,"YYYY/MM/DD) i get and error that said dateObject.format its not a function . 
how can i solve this ?

**Comment by fingerpich** [comment]
Please make a demo for you questions
