### ISSUE TITLE
strange behavior

### ISSUE THREAD

**Issue by unosbaghaie** [fingerpich/jalali-angular-datepicker#88]
hi

I have used datepicker , when I open and select a date to insert, the values are in jalaali date,
then i open edit form and save . the dates are in jalaali
but when I open edit form, and change the date, date value is in Gregorian.

why its behavior is like that ?

**Comment by fingerpich** [comment]
Please make a demo
I didn't understand the problem but I think you might better look at [jalali-moment](https://github.com/fingerpich/jalali-moment)
