### ISSUE TITLE
show Gregorian calendar

### ISSUE THREAD

**Issue by daliri72** [fingerpich/jalali-angular-datepicker#96]
How can I show Gregorian calendar in this date picker?

**Comment by fingerpich** [comment]
It's too obvious
Just change locale property 
[Demo](https://fingerpich.github.io/jalali-angular-datepicker/)

**Comment by fingerpich** [comment]
Hi,

I looked at the document and I can't find anything special about locale, sorry it wasn't that obvious.
I fixed the [demo](https://stackblitz.com/edit/angular-l7g3tq)
