### ISSUE TITLE
Time picker directive 

### ISSUE THREAD

**Issue by masoudDaliriyan** [fingerpich/jalali-angular-datepicker#99]
Make sure to add **all the information needed to understand the bug** so that someone can help. If the info is missing we'll add the 'Needs more information' label and close the issue until there is enough information.

- [ ] Provide a **minimal code snippet**, please make sure it is well formatted.
- [ ] Provide a **stackblitz** demo / [stackblitz](https://stackblitz.com/) example that reproduces the bug.
- [ ] Provide **screenshots** where appropriate
- [ ] What's the **version** of Angular you're using?
- [ ] Does this occur on specific browser?

**Comment by masoudDaliriyan** [comment]
two-way binding does not work between input and dpDayPicker directive but when close and reopen date-picker keep the value that in an input.
this issue exists at demo https://fingerpich.github.io/jalali-angular-datepicker/# at Time Picker directive section

**Comment by fingerpich** [comment]
Hi,
I changed the textbox and also selected days in picker modal and it was ok in the demo
Can you explain more? or use screen shots?
